version: '3.8'

services:
  mysql:
    container_name: mysql-job-nest
    image: mysql:latest
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - $DB_MYSQL_PORT:$DOCKER_DB_MYSQL_PORT
    volumes:
      - mysql_data:/var/lib/mysql
