export const ENV = {
  DATABASE_URL: 'DATABASE_URL',

  PORT: 'PORT',
  URL: 'URL',
  PREFIX: 'PREFIX',

  loggingEnable: 'loggingEnable',

  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME',
  AWS_BUCKET_REGION: 'AWS_BUCKET_REGION',
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',

  AUTH_SALT_ROUND: 'AUTH_SALT_ROUND',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  ACCESS_TOKEN_LIFE: 'ACCESS_TOKEN_LIFE',
  REFRESH_TOKEN_LIFE: 'REFRESH_TOKEN_LIFE',
};
