export const ENV = {
  DOMAIN: 'DOMAIN',

  DATABASE_URL: 'DATABASE_URL',

  PORT: 'PORT',
  URL: 'URL',
  PREFIX: 'PREFIX',

  loggingEnable: 'loggingEnable',

  //AWS
  AWS_BUCKET_NAME: 'AWS_BUCKET_NAME',
  AWS_BUCKET_REGION: 'AWS_BUCKET_REGION',
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',

  //AUTH
  COMMON_TOKEN_SECRET: 'COMMON_TOKEN_SECRET',
  AUTH_SALT_ROUND: 'AUTH_SALT_ROUND',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  ACCESS_TOKEN_LIFE: 'ACCESS_TOKEN_LIFE',
  REFRESH_TOKEN_LIFE: 'REFRESH_TOKEN_LIFE',

  //MAIL
  MAIL_HOST: 'MAIL_HOST',
  MAIL_USERNAME: 'MAIL_USERNAME',
  MAIL_PASSWORD: 'MAIL_PASSWORD',
};
